language: python
cache: pip

# Use container-based infrastructure
sudo: false

matrix:
  include:
   - env: TOXENV=py34-dj18
     python: 3.4
   - env: TOXENV=py35-dj19
     python: 3.5
   - env: TOXENV=py34-dj18
     python: 3.4
   - env: TOXENV=py35-dj19
     python: 3.5
   - env: TOXENV=flake8
     python: 3.5
   - env: TOXENV=isort
     python: 3.5
   - env: TOXENV=docs
     python: 3.5

# Package installation
install:
  - pip install tox

# Run the tests
script:
  tox
