language: python
cache: pip

# Use container-based infrastructure
sudo: false

matrix:
  include:
   - env: TOXENV=py34-dj{111,20}
     python: 3.4
   - env: TOXENV=py35-dj{111,20}
     python: 3.5
   - env: TOXENV=py36-dj{111,20}
     python: 3.6
   - env: TOXENV=flake8,isort,docs
     python: 3.6

# Package installation
install:
  - pip install tox

# Run the tests
script:
  tox
